<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{

	public function nameExist($team)
	{
		try {
			$query = $this->createQueryBuilder("t")
				->select("COUNT(t.id)")
				->where("t.name LIKE :name")
				->setParameter("name","%{$team->getName()}%");

			if (is_null($team->getId())) {
				return (bool) $query->getQuery()
					->getSingleScalarResult();
			} else {
				return (bool) $query->andWhere("t.id != :id")
					->setParameter("id", (int) $team->getId())
					->getQuery()
					->getSingleScalarResult();
			}
		}
		catch (\Exception $e) {
			return true;
		}
	}
}
