<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{

	public function nameExist($name)
	{

		$query = $this->createQueryBuilder('t')
					  ->select('t')
					  ->where('t.name LIKE :name')
					  ->setParameter('name',"%{$name}%")
					  ->setMaxResults(1)
					  ->getQuery()
					  ->getOneOrNullResult();


		return $query;

	}

}
